#
# before_install
# install
# before_script
# script
# after_failure
# after_success
# after_script
# env (though not yet excludes/includes or language-specific axes)
#
#
#
#
env:
  - env
before_install:
  - echo "before_install"
install:
  - echo "Install"
  - docker ps

before_script:
  - echo "Before_script"


script:
  - echo script
  - ls
  - docker build -t test .

after_success:
  - echo "successful build deploying"

foo: bar
